//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pavilions
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pavilions()
        {
            this.Arenda = new HashSet<Arenda>();
        }
    
        public int IDPavilion { get; set; }
        public string NumPavilion { get; set; }
        public Nullable<int> FloorPav { get; set; }
        public string NameSC { get; set; }
        public Nullable<int> IDStatusPavilions { get; set; }
        public Nullable<double> Square { get; set; }
        public Nullable<double> CostSqMPav { get; set; }
        public Nullable<double> CoeffAddValuePav { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arenda> Arenda { get; set; }
        public virtual StatusPavilions StatusPavilions { get; set; }
    }
}
