//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KingIT
{
    using System;
    using System.Collections.Generic;
    
    public partial class SC
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public SC()
        {
            this.Arenda = new HashSet<Arenda>();
        }
    
        public int IDSC { get; set; }
        public string NameSC { get; set; }
        public Nullable<int> IDStatusSC { get; set; }
        public Nullable<int> NumOfPavilionsSC { get; set; }
        public string TownSC { get; set; }
        public Nullable<double> CostSC { get; set; }
        public Nullable<double> CoeffAddValueSC { get; set; }
        public Nullable<int> IDPavilion { get; set; }
        public Nullable<int> NumOfFloorsSC { get; set; }
        public string ImageSC { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Arenda> Arenda { get; set; }
        public virtual StatusSC StatusSC { get; set; }
    }
}
